baseurl: "/"
title: "Home"
theme: "ghostwriter"
copyright: Chieroz
googleAnalytics: "UA-89722916-3"

author:
  name: "Chieroz"
  facebook: "https://facebook.com/chieroz"
  twitter: "https://twitter.com/chieroz"
  email: "contact@hugo.local"
  location: Torino

params:
  mainSections: ["post"]
  intro: true
  headline: "Blog di Chieroz"
  description: "Sto imparando a usare Hugo"
  github: "https://github.com/chieroz"
  twitter: "https://twitter.com/chieroz"
  email: "carlomario@chierotti.it"
  opengraph: true
  shareTwitter: true
  dateFormat: "Mon, Jan 2, 2006"

permalinks:
  post: "/:filename/"

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Articoli"
      url: "/article/"
      weight: 2
    - name: "Media"
      url: "/media"
      weight: 3
    - name: "Pagine"
      url: "/page/"
      weight: 4
    - name: "Contact"
      url: "/page/contact/"
      weight: 10
    - name: "About"
      url: "/page/about/"
      weight: 20
