baseurl = "/"
title = "Home"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Blog di Chieroz"
    description = "Sto imparando a usare Hugo"
    github = "https://github.com/chieroz"
    twitter = "https://twitter.com/chieroz"
    email = "carlomario@chierotti.it"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"
