build:
  publish: public
  command: hugo --gc --minify
context:
  production:
    environment:
      HUGO_VERSION: 0.74.3
      HUGO_ENV: production
      HUGO_ENABLEGITINFO: "true"
  split1:
    command: hugo --gc --minify --enableGitInfo
    environment:
      HUGO_VERSION: 0.74.3
      HUGO_ENV: production
  deploy-preview:
    command: hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL
    environment:
      HUGO_VERSION: 0.74.3
  branch-deploy:
    command: hugo --gc --minify -b $DEPLOY_PRIME_URL
    environment:
      HUGO_VERSION: 0.74.3
  next:
    environment:
      HUGO_ENABLEGITINFO: "true"
